### ISSUE TITLE
plotDesikanVolOnSurface and desikan_atlas_32k.dscalar.nii are not available

### ISSUE THREAD

**Issue by JujiaoKang** [kevmanderson/2020_PNAS_Depression#1]
Hi there! I'm running 02_ukb_mdd_pheno_plots.R to make brain maps. But "/gpfs/milgram/project/holmes/kma52/ukb_pymood/ref_files/desikan_atlas_32k.dscalar.nii" and the “plotDesikanVolOnSurface" function are not available . Could you please upload them? 
Thanks so much!

**Comment by kevmanderson** [comment]
Thanks for catching this! I've added both to the project repo:



Script: 
https://github.com/kevmanderson/2020_PNAS_Depression/blob/1646350d9e0be617bb9c9458b39038a491491e3b/scripts/util/plotDesikanVolOnSurface.m

^^There is a local dependency pointing to the gifti MATLAB library (https://www.artefact.tk/software/matlab/gifti/). Change this for your local version when running. 

dscalar: 
https://github.com/kevmanderson/2020_PNAS_Depression/blob/af1f22e5e1b306a1608e9318e86839a703aebcf7/reference_files/desikan_atlas_32k.dscalar.nii

Let me know if this doesn't do the trick.

-Kevin

**Comment by JujiaoKang** [comment]
Thank you for your answer!
I have downloaded these files. I will try it.

Thank you!
-Jujiao
